# Site settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "Photo Grid - Grid Gallery For Hugo"
theme = "photo-grid"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[params]
    # Meta
    no_exif = true
    title = "Photo Grid - Grid Gallery"
    subtitle = "This is my personal website to show my photos. Please enjoy!"
    author = "Chengsheng Deng"
    description = "Photo Grid - Shot on iPhone 12ProMax"
    keywords = "Hugo, Hugo theme, grid theme, gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io), [Pavel](https://themes.gohugo.io/hugrid/) and [me](https://chen-zhe.github.io)."
