# Site settings
baseurl = "https://dylanphotogallery.netlify.app/"
languageCode = "en-us"
title = "Photo Memories"
theme = "Shot On iPhone"
googleAnalytics = "UA-178433381-4"

[params]
    # Meta
    no_exif = false
    title = "Photo Grid - Grid Gallery"
    subtitle = "Chengsheng Deng"
    author = "Chengsheng Deng"
    description = "Photo Grid - Shot on iPhone 12ProMax"
    keywords = "Hugo, Hugo theme, grid theme, gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    footertext = "Made by Chengsheng Deng."
