# Site settings
baseurl = "http://example.org/"
languageCode = "en-us"
title = "Photo Grid - Grid Gallery For Hugo"
theme = "photo-grid"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[params]
    # Meta
    no_exif = false
    title = "Photo Grid - Grid Gallery"
    subtitle = "I made this website to share some photos I shot in Boston"
    author = "Chengsheng Deng"
    description = "Photo Grid - Shot on iPhone 12ProMax"
    keywords = "Hugo, Hugo theme, grid theme, gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    footertext = "Made by Chengsheng Deng."
